# [cmake]
# https://github.com/starship/starship/pull/1787
# symbol = "ğŸ”º "

[conda]
symbol = "ï„Œ "

[elm]
symbol = "î˜¬ "

[git_branch]
symbol = "ï˜ "

[hg_branch]
symbol = "ï˜ "

[julia]
symbol = "î˜¤ "

[memory_usage]
symbol = "ï¡š "

[nodejs]
symbol = "î‰ "

[status]
# Adjust spacing
symbol = "âœ– "
not_executable_symbol	= "ğŸš« "
not_found_symbol = "ğŸ” "
sigint_symbol = "ğŸ§± "
map_symbol = true
disabled = false

